-- Generated by nwg-displays on 2026-06-09 at 11:51:38. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@48.0",
    position = "0x0",
    scale = 1.67,
    transform = 1
})
